# Generated by Django 5.2.8 on 2026-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['organization', 'level', 'name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='class',
            name='classes_display_64e519_idx',
        ),
        migrations.RemoveField(
            model_name='class',
            name='display_order',
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['level'], name='classes_level_2956c4_idx'),
        ),
    ]
