# Generated by Django 5.2.8 on 2026-04-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_class_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='current_school_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Studying School Name'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='current_studying_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Studying Class'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_id_card_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's QID/Passport Number"),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_qid_back',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/father_qid/%Y/%m/', verbose_name='Father QID/Passport Back'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='father_qid_front',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/father_qid/%Y/%m/', verbose_name='Father QID/Passport Front'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='student_qid_back',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/qid/%Y/%m/', verbose_name='Student QID/Passport Back'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='student_qid_front',
            field=models.ImageField(blank=True, null=True, upload_to='registrations/qid/%Y/%m/', verbose_name='Student QID/Passport Front'),
        ),
    ]
