# Generated by Django 5.2.8 on 2026-04-16 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staff_multi_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('id_card_type', models.CharField(choices=[('QID', 'Qatar ID'), ('PASSPORT', 'Passport')], max_length=10)),
                ('id_card_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_registrations/photos/%Y/%m/')),
                ('qid_front', models.ImageField(blank=True, null=True, upload_to='staff_registrations/qid/%Y/%m/', verbose_name='QID/Passport Front')),
                ('qid_back', models.ImageField(blank=True, null=True, upload_to='staff_registrations/qid/%Y/%m/', verbose_name='QID/Passport Back')),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('qatar_address', models.JSONField(blank=True, default=dict)),
                ('india_address', models.JSONField(blank=True, default=dict)),
                ('religious_academic_details', models.TextField(blank=True, null=True)),
                ('academic_details', models.TextField(blank=True, null=True)),
                ('previous_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('msr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSR Number')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INFO_REQUESTED', 'Information Requested')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('info_request_message', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_registrations',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='staffprofile',
            name='staff_profi_branch__3328d7_idx',
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_registrations', to='main.organization'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffregistration',
            index=models.Index(fields=['organization', 'status'], name='staff_regis_organiz_205ef4_idx'),
        ),
        migrations.AddIndex(
            model_name='staffregistration',
            index=models.Index(fields=['submission_date'], name='staff_regis_submiss_00decb_idx'),
        ),
    ]
